// <auto-generated />
using GamesCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesCRUD.DataMigrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20260531022634_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GamesCRUD.Models.Games", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("genreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("genreId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("GamesCRUD.Models.Genre", b =>
                {
                    b.Property<int>("genreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("genreId");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("GamesCRUD.Models.Games", b =>
                {
                    b.HasOne("GamesCRUD.Models.Genre", "genre")
                        .WithMany()
                        .HasForeignKey("genreId");

                    b.Navigation("genre");
                });
#pragma warning restore 612, 618
        }
    }
}
